name: cb18
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - attrs=18.2.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.0.2=py_0
  - bzip2=1.0.6=h470a237_2
  - ca-certificates=2018.11.29=ha4d7672_0
  - certifi=2018.11.29=py37_1000
  - cffi=1.11.5=py37h5e8e0c9_1
  - cycler=0.10.0=py_1
  - dbus=1.13.0=h3a4f0e9_0
  - decorator=4.3.0=py_0
  - entrypoints=0.2.3=py37_1002
  - expat=2.2.5=hfc679d8_2
  - fontconfig=2.13.1=h65d0f4c_0
  - freetype=2.9.1=h6debe1e_4
  - gettext=0.19.8.1=h5e8e0c9_1
  - glib=2.56.2=h464dc38_1
  - gmp=6.1.2=hfc679d8_0
  - gst-plugins-base=1.12.5=hde13a9d_0
  - gstreamer=1.12.5=h5856ed1_0
  - icu=58.2=hfc679d8_0
  - ipykernel=5.1.0=py37h24bf2e0_1001
  - ipython=7.2.0=py37h24bf2e0_1000
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.4.2=py_0
  - jedi=0.13.1=py37_1000
  - jinja2=2.10=py_1
  - jpeg=9c=h470a237_1
  - jsonschema=3.0.0a3=py37_1000
  - jupyter=1.0.0=py_1
  - jupyter_client=5.2.4=py_0
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.4.0=py_0
  - kiwisolver=1.0.1=py37h2d50403_2
  - libffi=3.2.1=hfc679d8_5
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libiconv=1.15=h470a237_3
  - libpng=1.6.36=ha92aebf_0
  - libsodium=1.0.16=h470a237_1
  - libtiff=4.0.10=he6b73bb_0
  - libuuid=2.32.1=h470a237_2
  - libxcb=1.13=h470a237_2
  - libxml2=2.9.8=h422b904_5
  - markupsafe=1.1.0=py37h470a237_0
  - matplotlib=3.0.2=py37h8a2030e_1
  - matplotlib-base=3.0.2=py37h20b835b_1
  - mistune=0.8.4=py37h470a237_0
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hfc679d8_2
  - ninja=1.8.2=h2d50403_1
  - notebook=5.7.2=py37_1000
  - olefile=0.46=py_0
  - openblas=0.3.3=ha44fe06_1
  - openssl=1.0.2p=h470a237_1
  - pandas=0.23.4=py37hf8a1672_0
  - pandoc=2.5=0
  - pandocfilters=1.4.2=py_1
  - parso=0.3.1=py_0
  - pcre=8.41=hfc679d8_3
  - pexpect=4.6.0=py37_1000
  - pickleshare=0.7.5=py37_1000
  - pillow=5.3.0=py37hc736899_0
  - pip=18.1=py37_1000
  - prometheus_client=0.5.0=py_0
  - prompt_toolkit=2.0.7=py_0
  - pthread-stubs=0.4=h470a237_1
  - ptyprocess=0.6.0=py37_1000
  - pycparser=2.19=py_0
  - pygments=2.3.0=py_0
  - pyparsing=2.3.0=py_0
  - pyqt=5.6.0=py37h8210e8a_7
  - pyrsistent=0.14.7=py37h470a237_0
  - python=3.7.1=h5001a0f_0
  - python-dateutil=2.7.5=py_0
  - pytz=2018.7=py_0
  - pyzmq=17.1.2=py37hae99301_1
  - qt=5.6.2=hf70d934_9
  - qtconsole=4.4.3=py_0
  - readline=7.0=haf1bffa_1
  - send2trash=1.5.0=py_0
  - setuptools=40.6.2=py37_0
  - sip=4.18.1=py37hfc679d8_0
  - six=1.12.0=py37_1000
  - sqlite=3.26.0=hb1c47c0_0
  - terminado=0.8.1=py37_1001
  - testpath=0.4.2=py37_1000
  - tk=8.6.9=ha92aebf_0
  - tornado=5.1.1=py37h470a237_0
  - traitlets=4.3.2=py37_1000
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.32.3=py37_0
  - widgetsnbextension=3.4.2=py37_1000
  - xorg-libxau=1.0.8=h470a237_6
  - xorg-libxdmcp=1.1.2=h470a237_7
  - xz=5.2.4=h470a237_1
  - zeromq=4.2.5=hfc679d8_6
  - zlib=1.2.11=h470a237_3
  - pytorch=1.0.0=py3.7_cuda9.0.176_cudnn7.4.1_1
  - torchvision=0.2.1=py_2
  - blas=1.0=mkl
  - intel-openmp=2019.1=144
  - libgcc-ng=8.2.0=hdf63c60_1
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.4=py37h4414c95_1
  - mkl_random=1.0.1=py37h4414c95_1
  - numpy=1.15.4=py37h1d66e8a_0
  - numpy-base=1.15.4=py37h81de0dd_0
  - scikit-learn=0.20.1=py37h4989274_0
  - scipy=1.1.0=py37hfa4b5c9_1
  - pip:
    - torch==1.0.0

